version: 2
models:
  - name: users
    columns:
      - name: id
        tests:
          - unique
          - not_null
    meta:
      hightouch:
        model:
          id: 5
        destinations:
          - id: 2
            config:
              table: public.users
              mappings: []
            schedule:
              type: interval
              unit: week
              quantity: 12
  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: status
        tests:
          - accepted_values:
              values:
                - placed
                - shipped
                - completed
                - return_pending
                - returned
  - name: stg_payments
    columns:
      - name: payment_id
        tests:
          - unique
          - not_null
      - name: payment_method
        tests:
          - accepted_values:
              values:
                - credit_card
                - coupon
                - bank_transfer
                - gift_card
